// Batch 2, Part F: Trees, Trie, Greedy/Heap, Backtracking, Graphs, DP
// All statements, formats and tests are authored for ChainCode (stdin/stdout judging).
export const problemsF = [
  {
    title: "Path Sum II",
    difficulty: "Medium",
    topics: "Tree, DFS, Backtracking, Binary Tree",
    statement:
      "Collect every root-to-leaf path whose values sum exactly to `targetSum`. Output paths in the order a left-first DFS discovers them.",
    input: "Line 1: integer `targetSum`.\nLine 2: level-order tree tokens (values or `null`), space-separated on one line.",
    output: "Line 1: number of qualifying paths.\nThen one path per line: values space-separated.",
    constraints: ["-1000 <= node values, targetSum <= 1000", "1 <= node count <= 500"],
    hint: "DFS carrying the running sum and current trail; append the trail at leaves that land exactly on target.",
    tests: [
      { input: "22\n5 4 8 11 null 13 4 7 2 null null 5 1", output: "2\n5 4 11 2\n5 8 4 5" },
      { input: "5\n1 2 3", output: "0" },
      { input: "0\n1 2 3", output: "0" },
    ],
  },
  {
    title: "Binary Tree Maximum Path Sum",
    difficulty: "Hard",
    topics: "Tree, DFS, DP, Binary Tree",
    statement:
      "A path is any chain of adjacent nodes visiting each node at most once; it need not pass the root nor reach a leaf. Maximise the sum of node values along such a path.",
    input: "Line 1: level-order tree tokens (values or `null`).",
    output: "Print the maximum path sum.",
    constraints: ["1 <= node count <= 3*10^4", "-1000 <= values <= 1000"],
    hint: "Each node answers two questions: best downward arm through me (for my parent), and best total path arcing over me (global answer).",
    tests: [
      { input: "1 2 3", output: "6" },
      { input: "-10 9 20 null null 15 7", output: "42" },
      { input: "-3", output: "-3" },
    ],
  },
  {
    title: "Lowest Common Ancestor of a Binary Tree",
    difficulty: "Medium",
    topics: "Tree, DFS, Binary Tree",
    statement:
      "For a general binary tree (no ordering guarantees), find the lowest node having both `p` and `q` as descendants — a node counts as its own descendant. All values are distinct and both targets exist.",
    input: "Line 1: level-order tree tokens.\nLine 2: integers `p q`.",
    output: "Print the LCA node's value.",
    constraints: ["2 <= node count <= 10^5", "-10^9 <= values <= 10^9", "All values unique."],
    hint: "Post-order recursion returns a non-null witness when a subtree contains p, q, or the meeting point of both.",
    tests: [
      { input: "3 5 1 6 2 0 8 null null 7 4\n5 1", output: "3" },
      { input: "3 5 1 6 2 0 8 null null 7 4\n5 4", output: "5" },
      { input: "1 2\n1 2", output: "1" },
    ],
  },
  {
    title: "Construct Binary Tree from Inorder and Postorder Traversal",
    difficulty: "Medium",
    topics: "Array, Tree, Hash Table, Divide and Conquer",
    statement:
      "A binary tree's inorder and postorder traversals are given (values distinct). Rebuild the tree and print it in level order using our canonical token format (`null` placeholders).",
    input: "Line 1: integer `n`.\nLine 2: `n` inorder values.\nLine 3: `n` postorder values. Values are distinct.",
    output: "One line: level-order tokens of the rebuilt tree, with trailing structure preserved (no trailing `null`s beyond what's structural).",
    constraints: ["1 <= n <= 3000", "-3000 <= values <= 3000"],
    hint: "Postorder's last value is the root; its position in inorder splits left/right subtrees — recurse on slices (or index ranges) bottom-up.",
    tests: [
      { input: "5\n9 3 15 20 7\n9 15 7 20 3", output: "3 9 20 null null 15 7" },
      { input: "1\n2\n2", output: "2" },
      { input: "3\n1 2 3\n1 3 2", output: "2 1 3" },
    ],
  },
  {
    title: "Count Complete Tree Nodes",
    difficulty: "Easy",
    topics: "Tree, Binary Search, Binary Tree",
    statement:
      "Count nodes of a complete binary tree (every level full except possibly the last, which packs left). Better than O(n)? Exploit completeness: equal-height subtrees mean perfect halves you can count by formula.",
    input: "Line 1: level-order tree tokens (values are small positive ints or `null`).",
    output: "Print the node count.",
    constraints: ["0 <= node count <= 5*10^4"],
    hint: "Walk extreme-left and extreme-right depths from each root: if they match the subtree is perfect (2^h − 1); else recurse on both sides.",
    tests: [
      { input: "1 2 3 4 5 6", output: "6" },
      { input: "", output: "0" },
      { input: "1", output: "1" },
    ],
  },
  {
    title: "Flatten Binary Tree to Linked List",
    difficulty: "Medium",
    topics: "Tree, DFS, Stack, Linked List, Binary Tree",
    statement:
      "Morph the tree so every node's right child chains to its preorder successor and every left child is gone. Print the resulting right-spine top to bottom.",
    input: "Line 1: level-order tree tokens.",
    output: "One line: the flattened sequence of values space-separated.",
    constraints: ["1 <= node count <= 2000"],
    hint: "Preorder traversal is exactly the target order — either relink while traversing, or repeatedly fold each node's left subtree between node and right child.",
    tests: [
      { input: "1 2 5 3 4 null 6", output: "1 2 3 4 5 6" },
      { input: "", output: "" },
      { input: "0", output: "0" },
    ],
  },
  {
    title: "Unique Binary Search Trees",
    difficulty: "Medium",
    topics: "Tree, DP, Math, Catalan Number",
    statement:
      "How many structurally distinct BSTs store exactly the values 1..n?",
    input: "One line: integer `n`.",
    output: "Print the count.",
    constraints: ["1 <= n <= 19"],
    hint: "Catalan recurrence: pick each value as root once — trees(n) = Σ trees(i−1)·trees(n−i).",
    tests: [
      { input: "3", output: "5" },
      { input: "1", output: "1" },
      { input: "19", output: "1767263190" },
    ],
  },
  {
    title: "Implement Trie (Prefix Tree)",
    difficulty: "Medium",
    topics: "Hash Table, String, Design, Trie",
    statement:
      "Simulate a trie: `insert w`, `search w` (exact word stored?), `startswith p` (some stored word begins with p?). Echo results of search/startswith.",
    input: "Line 1: integer `q`.\nNext `q` lines: one operation each. Lowercase words only.",
    output: "One true/false line per search/startswith call.",
    constraints: ["1 <= q <= 100", "1 <= word length <= 20 (insert); startswith/search words may be length 1..20."],
    hint: "Nodes hold children maps plus an end-of-word flag; searching must check the flag, prefix checks need not.",
    tests: [
      { input: "7\ninsert apple\nsearch apple\nsearch app\nstartswith app\ninsert app\nsearch app\nsearch banana", output: "true\nfalse\ntrue\ntrue\nfalse" },
      { input: "3\ninsert a\nsearch a\nstartswith b", output: "true\nfalse" },
    ],
  },
  {
    title: "Word Search II",
    difficulty: "Hard",
    topics: "String, Backtracking, Trie, Matrix",
    statement:
      "Given a letter grid and a word list, report every list word traceable in the grid via adjacent cells without reusing a cell within one word.",
    input: "Line 1: integers `r c`.\nNext `r` lines: strings of exactly `c` lowercase letters.\nNext line: integer `m`.\nLast line: `m` space-separated words.",
    output: "Found words in alphabetical order, one per line.",
    constraints: ["1 <= r, c <= 12", "1 <= m <= 3*10^4", "1 <= word length <= 10", "All test words distinct."],
    hint: "Load words into a trie and walk the grid once with DFS — prune branches whose trie node died and un-mark cells when backtracking.",
    tests: [
      { input: "4 4\noath\npea\neat\nrain\n4\noath pea eat rain", output: "eat\noath" },
      { input: "2 2\nab\nba\n2\nabbb aaab", output: "" },
      { input: "1 1\na\n1\na", output: "a" },
    ],
  },
  {
    title: "Reorganize String",
    difficulty: "Medium",
    topics: "Hash Table, String, Greedy, Sorting, Heap, Counting",
    statement:
      "Rearrange the string's letters so no two identical characters sit adjacent. If impossible print `IMPOSSIBLE`. Among valid arrangements any one is accepted only if deterministic tests apply — ours do: always place the most frequent remaining character that differs from the last placed (ties broken alphabetically), which yields a unique output for every test below.",
    input: "One line: string `s` (lowercase letters).",
    output: "The rearranged string, or `IMPOSSIBLE` if no arrangement avoids adjacent duplicates.",
    constraints: ["1 <= s.length <= 500"],
    hint: "Feasibility: max frequency ≤ ceil(len/2). A max-heap of counts alternating placements builds an answer greedily.",
    tests: [
      { input: "aab", output: "aba" },
      { input: "aaab", output: "IMPOSSIBLE" },
      { input: "vvvlo", output: "vlvov" },
    ],
  },
  {
    title: "Task Scheduler",
    difficulty: "Medium",
    topics: "Array, Greedy, Heap, Counting",
    statement:
      "Tasks of named varieties run one per tick (or idle ticks happen). The same variety must sit at least `n` ticks apart (cooldown). Find the minimum number of ticks until all given tasks finish.",
    input: "Line 1: task string — letters concatenated, e.g. `AAABBB`.\nLine 2: cooldown `n`.",
    output: "Print the minimum total ticks.",
    constraints: ["1 <= tasks length <= 100", "0 <= n <= 100"],
    hint: "Frame the tallest letter columns: answer = max(len, (maxFreq−1)*(n+1) + howManyMax). Idles only exist inside that frame.",
    tests: [
      { input: "AAABBB\n2", output: "8" },
      { input: "ACABDB\n1", output: "6" },
      { input: "AAAAAAABCDEFG\n2", output: "16" },
    ],
  },
  {
    title: "Combination Sum II",
    difficulty: "Medium",
    topics: "Array, Backtracking",
    statement:
      "Candidates may contain duplicates but each may be used AT MOST ONCE per combination. List all unique combinations summing to the target (order inside a combination ascending; combinations lexicographic).",
    input: "Line 1: integers `m target`.\nLine 2: `m` space-separated candidates.",
    output: "Line 1: number of combinations.\nThen one combination per line in the defined order.",
    constraints: ["1 <= m <= 100", "1 <= candidates[i] <= 50", "1 <= target <= 30"],
    hint: "Sort first; skip a candidate identical to the previous sibling at the same depth, and never revisit earlier indexes.",
    tests: [
      { input: "7 8\n10 1 2 7 6 1 5", output: "4\n1 1 6\n1 2 5\n1 7\n2 6" },
      { input: "3 1\n2 5 2", output: "0" },
      { input: "2 2\n1 1", output: "1\n1 1" },
    ],
  },
  {
    title: "Restore IP Addresses",
    difficulty: "Medium",
    topics: "String, Backtracking",
    statement:
      "Split a digit string into four dot-separated parts forming valid IPv4-style octets (each part 0–255; no leading zeros unless the part is exactly '0'). List all ways.",
    input: "One line: digit string `s`.",
    output: "Line 1: number of valid addresses.\nThen one address per line in lexicographic order.",
    constraints: ["4 <= s.length <= 12", "Digits only."],
    hint: "Three cut points decide everything — backtrack over them validating each octet slice (length ≤ 3, range ≤ 255, no stray zero-prefix).",
    tests: [
      { input: "25525511135", output: "2\n255.255.11.135\n255.255.111.35" },
      { input: "0000", output: "1\n0.0.0.0" },
      { input: "101023", output: "5\n1.0.10.23\n1.0.102.3\n10.1.0.23\n10.10.2.3\n101.0.2.3" },
    ],
  },
  {
    title: "N-Queens Count",
    difficulty: "Hard",
    topics: "Backtracking, Chess",
    statement:
      "Place n queens on an n×n board so none attacks another (no shared row, column or diagonal). Print how many distinct boards achieve it.",
    input: "One line: integer `n`.",
    output: "Print the number of valid placements.",
    constraints: ["1 <= n <= 9"],
    hint: "Row-by-row backtracking tracking used columns and both diagonal id sets (r+c and r−c identify diagonals).",
    tests: [
      { input: "4", output: "2" },
      { input: "1", output: "1" },
      { input: "8", output: "92" },
    ],
  },
  {
    title: "Clone Graph",
    difficulty: "Medium",
    topics: "Hash Table, Graph, BFS, DFS",
    statement:
      "Deep-copy an undirected connected graph labelled 1..n. Output the clone's adjacency structure sorted — proving your copy preserves edges exactly.",
    input: "Line 1: integers `n m`.\nNext `m` lines: undirected edges `u v`.",
    output: "`n` lines: node i's neighbours ascending, space-separated (line may be empty for isolated nodes).",
    constraints: ["1 <= n <= 100", "No self loops or duplicate edges."],
    hint: "Hash map original→clone; BFS or DFS creating clones lazily keeps references consistent across cycles.",
    tests: [
      { input: "4 4\n1 2\n2 3\n3 4\n4 1", output: "2 4\n1 3\n2 4\n1 3" },
      { input: "1 0", output: "" },
      { input: "3 1\n2 3", output: "\n3\n2" },
    ],
  },
  {
    title: "Pacific Atlantic Water Flow",
    difficulty: "Medium",
    topics: "Matrix, DFS, BFS",
    statement:
      "Rain on cell (r,c) flows downhill (or flat) toward either ocean bordering the island matrix: Pacific touches the top row and left column; Atlantic the bottom row and right column. Water moves to equal-or-lower neighbour heights. Report every cell from which rain can reach BOTH oceans.",
    input: "Line 1: integers `m n`.\nNext `m` lines: `n` height values.",
    output: "Line 1: count of qualifying cells.\nThen one per line: `row col`, sorted by row then col.",
    constraints: ["1 <= m, n <= 200", "0 <= height <= 10^5"],
    hint: "Reverse the flow: flood inward FROM each ocean across non-decreasing heights; cells wetted by both floods qualify.",
    tests: [
      {
        input: "5 5\n1 2 2 3 5\n3 2 3 4 4\n2 4 5 3 1\n6 7 1 4 5\n5 1 1 2 4",
        output: "7\n0 4\n1 3\n1 4\n2 2\n3 0\n3 1\n4 0",
      },
      { input: "2 2\n1 1\n1 1", output: "4\n0 0\n0 1\n1 0\n1 1" },
      { input: "1 1\n5", output: "1\n0 0" },
    ],
  },
  {
    title: "Surrounded Regions",
    difficulty: "Medium",
    topics: "Matrix, DFS, BFS, Union Find",
    statement:
      "Board cells hold X or O. Flip every O that is fully surrounded by X (i.e., NOT connected to the board edge through O-cells) into X. Border-connected O regions survive.",
    input: "Line 1: integers `m n`.\nNext `m` lines: strings of X/O characters.",
    output: "The captured board, one row per line.",
    constraints: ["1 <= m, n <= 200"],
    hint: "Flood-fill border-touching Os marking them safe (e.g., '#'), sweep flipping the rest, then restore the safe marks.",
    tests: [
      { input: "4 4\nXXXX\nXOOX\nXXOX\nXOXX", output: "XXXX\nXXXX\nXXXX\nXOXX" },
      { input: "1 1\nX", output: "X" },
      { input: "2 2\nOO\nOO", output: "OO\nOO" },
    ],
  },
  {
    title: "Course Schedule II",
    difficulty: "Medium",
    topics: "Graph, Topological Sort, BFS, DFS",
    statement:
      "Order `n` courses respecting prerequisites `(a, b)` meaning b before a. When several courses are simultaneously available, take the smallest-numbered first (min-heap Kahn). Print the unique deterministic order, or IMPOSSIBLE when a cycle blocks completion.",
    input: "Line 1: integers `n m`.\nNext `m` lines: `a b` — course b precedes course a.",
    output: "One line: course numbers space-separated, or `IMPOSSIBLE`.",
    constraints: ["1 <= n <= 2000", "0 <= m <= 5000"],
    hint: "Kahn's algorithm with a priority queue instead of a plain queue gives the smallest-available tie-break for free.",
    tests: [
      { input: "4 4\n1 0\n2 0\n3 1\n3 2", output: "0 1 2 3" },
      { input: "2 2\n1 0\n0 1", output: "IMPOSSIBLE" },
      { input: "3 0", output: "0 1 2" },
    ],
  },
  {
    title: "Alien Dictionary",
    difficulty: "Hard",
    topics: "Graph, Topological Sort, String",
    statement:
      "Words arrive sorted according to an unknown alphabet. Recover ONE valid letter order — specifically the deterministic order produced by Kahn's algorithm taking the alphabetically-smallest available letter each step. Contradictions (cycle) or bad prefixes (longer word before its own prefix) make it impossible.",
    input: "Line 1: integer `m`.\nLine 2: `m` space-separated words (lowercase).",
    output: "One line: recovered letters in order, or `IMPOSSIBLE`.",
    constraints: ["1 <= m <= 100", "1 <= word length <= 20", "Only letters appearing in the words participate."],
    hint: "Compare adjacent word pairs to extract precedence edges, then topologically sort; the prefix violation case needs an explicit check.",
    tests: [
      { input: "5\nwrt wrf er ett rftt", output: "wertf" },
      { input: "2\nz x", output: "zx" },
      { input: "2\nabcd abc", output: "IMPOSSIBLE" },
    ],
  },
  {
    title: "Cheapest Flights Within K Stops",
    difficulty: "Medium",
    topics: "Graph, DP, Bellman-Ford, BFS, Heap",
    statement:
      "Fly from `src` to `dst` across directed priced flights using at most `k` intermediate stops. Find the minimum total price, or −1 when unreachable under the limit.",
    input: "Line 1: integers `n m src dst k`.\nNext `m` lines: `u v w` — flight u→v costing w. Nodes numbered 0..n−1.",
    output: "Print the minimum cost, or `-1`.",
    constraints: ["1 <= n <= 100", "0 <= k < n", "1 <= w <= 10^4"],
    hint: "Bellman-Ford limited to k+1 relaxation rounds (relax from a frozen copy) tracks cheapest-with-stop-budget cleanly.",
    tests: [
      { input: "4 5 0 3 1\n0 1 100\n1 2 100\n2 0 100\n1 3 600\n2 3 200", output: "700" },
      { input: "3 3 0 2 1\n0 1 100\n1 2 100\n0 2 500", output: "200" },
      { input: "3 3 0 2 0\n0 1 100\n1 2 100\n0 2 500", output: "500" },
    ],
  },
  {
    title: "Is Graph Bipartite?",
    difficulty: "Medium",
    topics: "Graph, BFS, DFS, Union Find, Coloring",
    statement:
      "Decide whether an undirected graph's nodes split into two groups where every edge crosses groups (equivalently: 2-colorable). Isolated nodes color freely.",
    input: "Line 1: integers `n m`.\nNext `m` lines: undirected edge `u v`.",
    output: "Print `true` if bipartite, else `false`.",
    constraints: ["1 <= n <= 100", "0 <= m <= n*(n-1)/2", "No self loops."],
    hint: "BFS-color alternately from each uncolored component; a neighbor ever matching the current color kills it.",
    tests: [
      { input: "4 4\n0 1\n1 2\n2 3\n3 0", output: "true" },
      { input: "4 5\n0 1\n0 2\n1 2\n2 3\n0 3", output: "false" },
      { input: "3 0", output: "true" },
    ],
  },
  {
    title: "Redundant Connection",
    difficulty: "Medium",
    topics: "Graph, Union Find, Tree",
    statement:
      "A tree on n nodes gained one extra edge (edges listed in order, nodes 1..n, no repeats). Return the LAST edge whose addition closed a cycle.",
    input: "Line 1: integer `m` (number of edges).\nNext `m` lines: edge endpoints `u v`.",
    output: "Print the offending edge as `u v`.",
    constraints: ["3 <= n <= 1000", "Edges form a tree plus exactly one extra edge."],
    hint: "Union-find over edges in order: the first pair already sharing a root is the cycle closer — and since just one extra edge exists, also the last.",
    tests: [
      { input: "3\n1 2\n1 3\n2 3", output: "2 3" },
      { input: "5\n1 2\n2 3\n3 4\n1 4\n1 5", output: "1 4" },
      { input: "3\n1 2\n2 3\n3 1", output: "3 1" },
    ],
  },
  {
    title: "Open the Lock",
    difficulty: "Medium",
    topics: "BFS, Hash Table, String",
    statement:
      "A 4-dial lock shows digits 0000–9999; one move turns a single dial up or down by one (mod 10). Certain combinations are deadends — touching one fails instantly. Start at 0000 and find the fewest moves to reach `target`, or −1 if impossible (including target being a deadend or 0000 itself being dead).",
    input: "Line 1: integer `d`.\nLine 2: `d` deadend codes space-separated (d may be 0 → empty line).\nLine 3: target code.",
    output: "Print minimum number of dial moves, or `-1`.",
    constraints: ["0 <= d <= 500", "Codes are four digits each."],
    hint: "Plain BFS over the 10^4 state space generating ±1 neighbours per wheel; hash the deadends and visited states together.",
    tests: [
      { input: "5\n0201 0101 0102 1212 2002\n0202", output: "6" },
      { input: "1\n8888\n0009", output: "1" },
      { input: "2\n8887 8889\n8888", output: "-1" },
      { input: "1\n0000\n0101", output: "-1" },
    ],
  },
  {
    title: "Shortest Path in Binary Matrix",
    difficulty: "Medium",
    topics: "Matrix, BFS, Graph",
    statement:
      "Walk an n×n grid of 0/1 from top-left to bottom-right moving in ANY of 8 directions onto clear (0) cells. Path length counts cells visited. Find the shortest such clear path, or −1. Cells (0,0) and (n−1,n−1) must themselves be clear.",
    input: "Line 1: integer `n`.\nNext `n` lines: `n` bits each.",
    output: "Print the path length (cell count), or `-1`.",
    constraints: ["1 <= n <= 10^5 conceptually; tests use n <= 100."],
    hint: "BFS from the corner with all eight offsets; first arrival at (n−1,n−1) is optimal because every step costs one.",
    tests: [
      { input: "2\n0 1\n1 0", output: "-1" },
      { input: "3\n0 0 0\n1 1 0\n1 1 0", output: "4" },
      { input: "1\n0", output: "1" },
      { input: "4\n0 0 0 0\n1 1 0 0\n1 1 0 0\n1 1 1 0", output: "4" },
    ],
  },
  {
    title: "Longest Increasing Path in a Matrix",
    difficulty: "Hard",
    topics: "Matrix, DFS, DP, Memoization, Topological Sort",
    statement:
      "Move between horizontally/vertically adjacent matrix cells only when the next value is STRICTLY greater. Find the longest path length measured in cells.",
    input: "Line 1: integers `m n`.\nNext `m` lines: `n` space-separated values.",
    output: "Print the longest strictly increasing path length.",
    constraints: ["1 <= m, n <= 200", "0 <= values <= 2^31 - 1"],
    hint: "Memoize dfs(r,c) = 1 + best of eligible neighbours; strictness makes the implicit DAG acyclic so memoization is sound.",
    tests: [
      { input: "3 3\n9 9 4\n6 6 8\n2 1 1", output: "4" },
      { input: "3 3\n3 4 5\n3 2 6\n2 2 1", output: "4" },
      { input: "1 1\n1", output: "1" },
    ],
  },
  {
    title: "Coin Change II",
    difficulty: "Medium",
    topics: "Array, DP",
    statement:
      "Unlimited coins of given denominations: count the COMBINATIONS (order ignored) summing to `amount`.",
    input: "Line 1: integers `m amount`.\nLine 2: `m` distinct coin denominations.",
    output: "Print the number of combinations.",
    constraints: ["1 <= m <= 300", "1 <= coins[i] <= 5000", "0 <= amount <= 5000"],
    hint: "Loop coins OUTER, amounts inner — swapping the loops would count permutations instead of combinations.",
    tests: [
      { input: "3 5\n1 2 5", output: "4" },
      { input: "1 3\n2", output: "0" },
      { input: "1 10\n10", output: "1" },
    ],
  },
  {
    title: "Jump Game II",
    difficulty: "Medium",
    topics: "Array, Greedy, DP, BFS",
    statement:
      "From index i you may jump forward up to nums[i] steps. Return the MINIMUM number of jumps needed to reach the last index (tests guarantee reachability).",
    input: "Line 1: integer `n`.\nLine 2: `n` non-negative jump lengths.",
    output: "Print the minimal jump count.",
    constraints: ["1 <= n <= 10^4", "0 <= nums[i] <= 1000", "End is always reachable."],
    hint: "Greedy layers: treat reachable range [lo..hi] as a BFS frontier; extend hi to the furthest next-reach and count layer crossings.",
    tests: [
      { input: "5\n2 3 1 1 4", output: "2" },
      { input: "5\n2 3 0 1 4", output: "2" },
      { input: "1\n0", output: "0" },
      { input: "3\n1 1 1", output: "2" },
    ],
  },
  {
    title: "Maximum Product Subarray",
    difficulty: "Medium",
    topics: "Array, DP",
    statement:
      "Find the contiguous subarray (non-empty) whose element PRODUCT is maximal.",
    input: "Line 1: integer `n`.\nLine 2: `n` space-separated integers.",
    output: "Print the maximum product.",
    constraints: ["1 <= n <= 2*10^4", "-10 <= nums[i] <= 10", "Answer fits in 32-bit signed."],
    hint: "Track running max AND min products — a huge negative flips roles the moment another negative appears.",
    tests: [
      { input: "4\n2 3 -2 4", output: "6" },
      { input: "3\n-2 0 -1", output: "0" },
      { input: "3\n-2 3 -4", output: "24" },
    ],
  },
  {
    title: "Longest Palindromic Subsequence",
    difficulty: "Medium",
    topics: "String, DP",
    statement:
      "Find the longest subsequence (not necessarily contiguous, order kept) of the string reading the same forwards and backwards.",
    input: "One line: string `s` (lowercase).",
    output: "Print the length of the longest palindromic subsequence.",
    constraints: ["1 <= s.length <= 1000"],
    hint: "Interval DP: ends matching add 2 around the interior; otherwise drop one end and keep the better.",
    tests: [
      { input: "bbbab", output: "4" },
      { input: "cbbd", output: "2" },
      { input: "agbdba", output: "5" },
    ],
  },
  {
    title: "Maximal Square",
    difficulty: "Medium",
    topics: "Matrix, DP",
    statement:
      "Locate the largest square block of 1s inside a binary matrix and print its AREA.",
    input: "Line 1: integers `m n`.\nNext `m` lines: strings of '0'/'1' characters, length n.",
    output: "Print the area of the biggest all-ones square (0 if none exists).",
    constraints: ["1 <= m, n <= 300"],
    hint: "dp[r][c] = side of largest square ending here = 1 + min(three upper-left neighbours) when the cell is 1.",
    tests: [
      { input: "4 5\n10100\n11111\n11110\n01111", output: "4" },
      { input: "2 2\n01\n10", output: "1" },
      { input: "1 1\n0", output: "0" },
    ],
  },
  {
    title: "Target Sum",
    difficulty: "Medium",
    topics: "Array, DP, Backtracking",
    statement:
      "Assign '+' or '-' before every array element so the evaluated expression equals `target`. Count how many distinct assignments work.",
    input: "Line 1: integers `n target`.\nLine 2: `n` non-negative integers.",
    output: "Print the number of sign assignments hitting the target.",
    constraints: ["1 <= n <= 20", "0 <= nums[i] <= 1000", "0 <= |target| <= 1000"],
    hint: "Subset-sum in disguise: positives P satisfy P − (S−P) = target, so count subsets summing (target+S)/2.",
    tests: [
      { input: "5 3\n1 1 1 1 1", output: "5" },
      { input: "1 1\n1", output: "1" },
      { input: "4 2\n1 2 3 4", output: "1" },
    ],
  },
  {
    title: "Partition to K Equal Sum Subsets",
    difficulty: "Medium",
    topics: "Array, DP, Bitmask, Backtracking",
    statement:
      "Decide whether the array splits into `k` non-empty groups of EQUAL sums (every element used exactly once).",
    input: "Line 1: integers `n k`.\nLine 2: `n` positive integers.",
    output: "Print `true` if such a partition exists, else `false`.",
    constraints: ["1 <= k <= n <= 16", "1 <= nums[i] <= 10^4"],
    hint: "Backtrack filling buckets one by one with pruning: skip duplicate bucket loads and elements exceeding the remaining quota.",
    tests: [
      { input: "7 4\n4 3 2 3 5 2 1", output: "true" },
      { input: "4 3\n1 2 3 4", output: "false" },
      { input: "4 2\n2 2 2 2", output: "true" },
    ],
  },
  {
    title: "Perfect Squares",
    difficulty: "Medium",
    topics: "Math, DP, BFS, Number Theory",
    statement:
      "Express `n` as a sum of perfect squares (1,4,9,...) minimising how many squares are used.",
    input: "One line: integer `n`.",
    output: "Print the minimal square count.",
    constraints: ["1 <= n <= 10^4"],
    hint: "fewest(x) = 1 + min over squares s≤x of fewest(x−s); Lagrange's theorem caps the true answer at 4.",
    tests: [
      { input: "12", output: "3" },
      { input: "13", output: "2" },
      { input: "1", output: "1" },
    ],
  },
  {
    title: "Meeting Rooms II",
    difficulty: "Medium",
    topics: "Array, Greedy, Sorting, Heap, Two Pointers",
    statement:
      "Given meeting intervals, compute the minimum number of rooms so no two overlapping meetings share one. A meeting ending exactly when another starts does NOT overlap.",
    input: "Line 1: integer `k`.\nNext `k` lines: interval `start end` (start < end).",
    output: "Print the minimum room count.",
    constraints: ["1 <= k <= 10^4", "0 <= start < end <= 10^6"],
    hint: "Sort starts and ends separately and sweep with two pointers; or sort by start and pop the heap whenever the earliest end frees a room (end == start frees it).",
    tests: [
      { input: "3\n0 30\n5 10\n15 20", output: "2" },
      { input: "2\n7 10\n2 4", output: "1" },
      { input: "3\n1 5\n5 8\n8 12", output: "1" },
    ],
  },
];
