// Batch 2, Part E: Sliding Window, Stack/Queue, Binary Search, Linked List
// All statements, formats and tests are authored for ChainCode (stdin/stdout judging).
export const problemsE = [
  {
    title: "Longest Repeating Character Replacement",
    difficulty: "Medium",
    topics: "Hash Table, String, Sliding Window",
    statement:
      "You may replace at most `k` characters in the string. Find the length of the longest window that can be made into a run of one repeated character using those replacements.",
    input: "Line 1: string `s` (uppercase letters).\nLine 2: integer `k`.",
    output: "Print the maximum achievable window length.",
    constraints: ["1 <= s.length <= 10^5", "0 <= k <= s.length"],
    hint: "A window is valid while windowLength − maxFrequency <= k; slide and never let the window shrink — it only grows.",
    tests: [
      { input: "ABAB\n2", output: "4" },
      { input: "AABABBA\n1", output: "4" },
      { input: "AAAA\n0", output: "4" },
    ],
  },
  {
    title: "Permutation in String",
    difficulty: "Medium",
    topics: "Hash Table, String, Sliding Window",
    statement:
      "Decide whether `s2` contains any contiguous window that is a permutation (anagram) of `s1`.",
    input: "Line 1: string `s1`.\nLine 2: string `s2` (both lowercase).",
    output: "Print `true` if such a window exists, else `false`.",
    constraints: ["1 <= s1.length, s2.length <= 10^4"],
    hint: "Count letter frequencies of s1, then sweep a fixed-size window across s2 updating counts incrementally.",
    tests: [
      { input: "ab\neidbaooo", output: "true" },
      { input: "ab\neidboaoo", output: "false" },
      { input: "a\na", output: "true" },
    ],
  },
  {
    title: "Minimum Window Substring",
    difficulty: "Hard",
    topics: "Hash Table, String, Sliding Window",
    statement:
      "Find the shortest substring of `t`'s container string that covers **all** characters of `t`, counting multiplicities. If no such window exists, print an empty line.",
    input: "Line 1: string `s`.\nLine 2: string `t` (both uppercase+lowercase latin).",
    output: "Print the minimum covering window, or an empty line if none exists. If several windows tie in length, the leftmost is unique in all tests.",
    constraints: ["1 <= s.length, t.length <= 10^5", "Ties are resolved uniquely by test design."],
    hint: "Expand right to satisfy every needed character, then contract left as far as validity allows — record each valid shrink.",
    tests: [
      { input: "ADOBECODEBANC\nABC", output: "BANC" },
      { input: "a\na", output: "a" },
      { input: "a\naa", output: "" },
    ],
  },
  {
    title: "Sliding Window Maximum",
    difficulty: "Hard",
    topics: "Array, Monotonic Queue, Heap, Sliding Window",
    statement:
      "For every window of `k` consecutive elements moving left to right through the array, report its maximum value.",
    input: "Line 1: integers `n k`.\nLine 2: `n` space-separated integers.",
    output: "The n−k+1 window maxima, space-separated on one line.",
    constraints: ["1 <= k <= n <= 10^5", "-10^4 <= nums[i] <= 10^4"],
    hint: "Keep a deque of indices with decreasing values; its front is always the current window's max.",
    tests: [
      { input: "8 3\n1 3 -1 -3 5 3 6 7", output: "3 3 5 5 6 7" },
      { input: "1 1\n1", output: "1" },
      { input: "5 2\n9 8 7 6 5", output: "9 8 7 6" },
    ],
  },
  {
    title: "Fruit Into Baskets",
    difficulty: "Medium",
    topics: "Array, Hash Table, Sliding Window",
    statement:
      "Walking along trees each bearing one fruit type, you collect fruits into two baskets that may hold unlimited amounts but only two distinct types in total. Once you pass a tree you cannot go back; find the longest stretch containing at most two distinct fruit types.",
    input: "Line 1: integer `n`.\nLine 2: `n` fruit type numbers.",
    output: "Print the maximum number of fruits you can pick consecutively.",
    constraints: ["1 <= n <= 10^5", "0 <= fruits[i] <= 10^5"],
    hint: "Classic 'longest window with at most 2 distinct values' — shrink from the left whenever a third type appears.",
    tests: [
      { input: "3\n1 2 1", output: "3" },
      { input: "4\n0 1 2 2", output: "3" },
      { input: "5\n1 2 3 2 2", output: "4" },
      { input: "10\n3 3 3 1 2 1 1 2 3 3 4", output: "5" },
    ],
  },
  {
    title: "3Sum Closest",
    difficulty: "Medium",
    topics: "Array, Two Pointers, Sorting",
    statement:
      "Among all triples of distinct indices, find the triple whose sum comes closest to `target`. The tests guarantee this closest sum is achieved uniquely as a value.",
    input: "Line 1: integers `n target`.\nLine 2: `n` space-separated integers.",
    output: "Print the closest achievable triple sum.",
    constraints: ["3 <= n <= 500", "-1000 <= nums[i] <= 1000", "-10^4 <= target <= 10^4"],
    hint: "Sort, fix the smallest element, then squeeze a two-pointer pair inward recording whichever sum beats the current best distance.",
    tests: [
      { input: "4 1\n-1 2 1 -4", output: "2" },
      { input: "3 1\n0 0 0", output: "0" },
      { input: "4 100\n1 1 1 0", output: "3" },
    ],
  },
  {
    title: "4Sum",
    difficulty: "Medium",
    topics: "Array, Two Pointers, Sorting",
    statement:
      "List all unique quadruples of distinct indices whose values sum to `target` (same values in different index groupings count once). Sort the array first; then output quadruples sorted lexicographically.",
    input: "Line 1: integers `n target`.\nLine 2: `n` space-separated integers.",
    output: "Line 1: the number of quadruples.\nThen one per line: four values space-separated, lexicographic order.",
    constraints: ["0 <= n <= 200", "-10^9 <= nums[i], target <= 10^9"],
    hint: "Nest two loops over sorted candidates and reduce the innermost pair to two pointers — skip equal neighbours to stay unique.",
    tests: [
      { input: "6 0\n1 0 -1 0 -2 2", output: "3\n-2 -1 1 2\n-2 0 0 2\n-1 0 0 1" },
      { input: "5 0\n2 2 2 2 2", output: "1\n2 2 2 2" },
      { input: "3 100\n1 2 3", output: "0" },
    ],
  },
  {
    title: "Median of Two Sorted Arrays",
    difficulty: "Hard",
    topics: "Array, Binary Search, Divide and Conquer",
    statement:
      "Given two individually sorted arrays of sizes m and n, compute the median of their merged order without actually merging (target O(log(min(m,n)))). Print it fixed to exactly five decimal places.",
    input: "Line 1: integers `m n`.\nLine 2: `m` sorted integers.\nLine 3: `n` sorted integers.",
    output: "The median, printed with exactly five decimal places.",
    constraints: ["0 <= m, n <= 1000 (not both zero)", "-10^6 <= values <= 10^6"],
    hint: "Binary-search how many elements the left half takes from the shorter array; the partition must keep both halves ordered crosswise.",
    tests: [
      { input: "2 1\n1 2\n3", output: "2.00000" },
      { input: "2 2\n1 2\n3 4", output: "2.50000" },
      { input: "1 0\n7", output: "7.00000" },
    ],
  },
  {
    title: "Find First and Last Position of Element in Sorted Array",
    difficulty: "Medium",
    topics: "Array, Binary Search",
    statement:
      "Locate the first and last occurrence (0-based) of `target` in a non-decreasing array, or both −1 when absent. Must be O(log n).",
    input: "Line 1: integers `n target`.\nLine 2: `n` non-decreasing integers.",
    output: "Print `first last` on one line, or `-1 -1`.",
    constraints: ["0 <= n <= 10^5", "-10^9 <= nums[i], target <= 10^9"],
    hint: "Two lower-bound style searches: one biased to the left edge, one to the right.",
    tests: [
      { input: "6 8\n5 7 7 8 8 10", output: "3 4" },
      { input: "6 6\n5 7 7 8 8 10", output: "-1 -1" },
      { input: "1 0\n0", output: "0 0" },
    ],
  },
  {
    title: "First Bad Version",
    difficulty: "Easy",
    topics: "Binary Search, Interactive",
    statement:
      "Versions are numbered 1..n; after some point every version is bad. You receive a quality string (`G` = good, `B` = bad) representing versions in order — badness persists once it starts. Minimise API-call-style probing: report the FIRST bad version's 1-based index.",
    input: "One line: string of characters `G`/`B` describing versions 1..n in order. At least one B is guaranteed.",
    output: "Print the 1-based index of the first bad version.",
    constraints: ["1 <= n <= 2^31 - 1 conceptually; tests use n <= 10^6."],
    hint: "Plain binary search for the boundary: while lo < hi, probe mid and discard the good half.",
    tests: [
      { input: "GGGBBB", output: "4" },
      { input: "GB", output: "2" },
      { input: "BBBB", output: "1" },
    ],
  },
  {
    title: "Search a 2D Matrix II",
    difficulty: "Medium",
    topics: "Matrix, Binary Search, Divide and Conquer",
    statement:
      "Each matrix row is sorted ascending AND each column is sorted ascending (rows do not concatenate like Search a 2D Matrix). Decide whether `target` appears.",
    input: "Line 1: integers `m n`.\nNext `m` lines: `n` space-separated integers (rows ascending, columns ascending).\nLast line: integer `target`.",
    output: "Print `true` if found, else `false`.",
    constraints: ["1 <= m, n <= 300", "-10^9 <= values, target <= 10^9"],
    hint: "Start at the top-right corner: larger targets force a step down, smaller ones a step left — O(m+n) total.",
    tests: [
      { input: "5 5\n1 4 7 11 15\n2 5 8 12 19\n3 6 9 16 22\n10 13 14 17 24\n18 21 23 26 30\n5", output: "true" },
      { input: "5 5\n1 4 7 11 15\n2 5 8 12 19\n3 6 9 16 22\n10 13 14 17 24\n18 21 23 26 30\n20", output: "false" },
      { input: "1 1\n1\n1", output: "true" },
    ],
  },
  {
    title: "Single Element in a Sorted Array",
    difficulty: "Medium",
    topics: "Array, Binary Search",
    statement:
      "Sorted array where exactly one element appears once and every other element appears twice, pairs sitting adjacent before and after the loner. Find the loner in O(log n) time and O(1) space.",
    input: "Line 1: odd integer `n`.\nLine 2: `n` non-decreasing integers.",
    output: "Print the element appearing once.",
    constraints: ["1 <= n <= 10^5", "0 <= nums[i] <= 10^5"],
    hint: "Pair partners live at even/even+1 indexes left of the loner and odd/even+1 right of it — binary search on that invariant.",
    tests: [
      { input: "9\n1 1 2 3 3 4 4 8 8", output: "2" },
      { input: "7\n3 3 7 7 10 11 11", output: "10" },
      { input: "1\n5", output: "5" },
    ],
  },
  {
    title: "Split Array Largest Sum",
    difficulty: "Hard",
    topics: "Array, Binary Search, DP, Greedy",
    statement:
      "Split the array (order preserved) into `k` non-empty consecutive parts so that the LARGEST part-sum is as small as possible. Print that minimized largest sum.",
    input: "Line 1: integers `n k`.\nLine 2: `n` non-negative integers.",
    output: "Print the minimal possible largest subarray sum.",
    constraints: ["1 <= k <= n <= 1000", "0 <= nums[i] <= 10^6"],
    hint: "Binary search the answer between max element and total; greedy-check whether k pieces can respect that cap.",
    tests: [
      { input: "5 2\n7 2 5 10 8", output: "18" },
      { input: "5 2\n1 2 3 4 5", output: "9" },
      { input: "3 3\n1 4 4", output: "4" },
    ],
  },
  {
    title: "Basic Calculator II",
    difficulty: "Medium",
    topics: "String, Math, Stack",
    statement:
      "Evaluate an arithmetic expression containing non-negative integers and the operators `+`, `-`, `*`, `/` (spaces may appear anywhere). Division truncates toward zero. No parentheses.",
    input: "One line: the expression (digits, operators, spaces). It represents a valid expression.",
    output: "Print the integer result.",
    constraints: ["1 <= s.length <= 3*10^5", "Intermediate and final results fit in 32-bit signed."],
    hint: "Push terms onto a stack: multiply/divide collapse instantly with the previous term; plus/minus defer signed terms until the end.",
    tests: [
      { input: "3+2*2", output: "7" },
      { input: " 3/2 ", output: "1" },
      { input: " 3+5 / 2 ", output: "5" },
      { input: "14-3/2", output: "13" },
    ],
  },
  {
    title: "Decode String",
    difficulty: "Medium",
    topics: "String, Stack, Recursion",
    statement:
      "An encoded string follows `k[encoded_string]`, meaning the bracketed content repeats k times (k is a positive integer). Patterns nest. Decode and print the original.",
    input: "One line: the encoded string (lowercase letters, digits, brackets). Input is always valid.",
    output: "Print the decoded string.",
    constraints: ["1 <= s.length <= 30", "Output stays under 10^6 characters.", "No unbalanced brackets."],
    hint: "Stacks of partial strings and repeat counts unwind nesting naturally when each closing bracket pops.",
    tests: [
      { input: "3[a]2[bc]", output: "aaabcbc" },
      { input: "3[a2[c]]", output: "accaccacc" },
      { input: "2[abc]3[cd]ef", output: "abcabccdcdcdef" },
    ],
  },
  {
    title: "Next Greater Element I",
    difficulty: "Easy",
    topics: "Array, Hash Table, Monotonic Stack",
    statement:
      "`nums1` is a subset of distinct values also present in `nums2`. For each x in nums1 report the next value to its right IN nums2 that is greater than x, or −1 if none.",
    input: "Line 1: integers `m n`.\nLine 2: `m` distinct integers (nums1, subset of nums2).\nLine 3: `n` distinct integers (nums2).",
    output: "The answers for nums1 in order, space-separated on one line.",
    constraints: ["1 <= m <= n <= 1000", "All values distinct within each array."],
    hint: "Precompute each nums2 element's next-greater once with a monotonic stack, then answer queries from a hash map.",
    tests: [
      { input: "3 4\n4 1 2\n1 3 4 2", output: "-1 3 -1" },
      { input: "2 4\n2 4\n1 2 3 4", output: "3 -1" },
      { input: "1 1\n5\n5", output: "-1" },
    ],
  },
  {
    title: "Next Greater Element II",
    difficulty: "Medium",
    topics: "Array, Stack, Monotonic Stack",
    statement:
      "Now the array is circular: the next greater element may wrap around past the end. For every position report the first strictly greater value scanning clockwise (possibly wrapping), or −1.",
    input: "Line 1: integer `n`.\nLine 2: `n` space-separated integers.",
    output: "The n answers, space-separated on one line.",
    constraints: ["1 <= n <= 10^4", "-10^9 <= nums[i] <= 10^9"],
    hint: "Iterate the doubled sequence 0..2n−1 modulo n with a monotonic stack — second pass resolves wraps.",
    tests: [
      { input: "3\n1 2 1", output: "2 -1 2" },
      { input: "5\n1 2 3 4 3", output: "2 3 4 -1 4" },
      { input: "1\n5", output: "-1" },
    ],
  },
  {
    title: "Online Stock Span",
    difficulty: "Medium",
    topics: "Stack, Design, Monotonic Stack, Data Stream",
    statement:
      "Daily price quotes arrive one by one. Each quote's span is the count of consecutive days (including today) whose price was less than or equal to today's, stopping before any earlier day with a strictly higher price. Simulate quotes and print each span.",
    input: "Line 1: integer `q`.\nNext `q` lines: `price x`.",
    output: "`q` lines, the i-th being the span after the i-th quote.",
    constraints: ["1 <= q <= 10^4", "1 <= x <= 10^5"],
    hint: "Pop stored days whose prices are ≤ today's while accumulating their spans — the stack keeps strictly decreasing prices.",
    tests: [
      { input: "7\nprice 100\nprice 80\nprice 60\nprice 70\nprice 60\nprice 75\nprice 85", output: "1\n1\n1\n2\n1\n4\n6" },
      { input: "3\nprice 50\nprice 50\nprice 50", output: "1\n2\n3" },
    ],
  },
  {
    title: "Implement Queue Using Stacks",
    difficulty: "Easy",
    topics: "Stack, Design, Queue",
    statement:
      "Simulate a FIFO queue built from stack operations: push appends, pop removes the front, peek reads the front, empty reports emptiness. Echo the results of pop, peek and empty calls. These calls are never issued on an empty queue except `empty` itself.",
    input: "Line 1: integer `q`.\nNext `q` lines: `push x`, `pop`, `peek` or `empty`. `push` x fits in 32-bit.",
    output: "One line per pop/peek/empty call: the popped/front value or true/false.",
    constraints: ["1 <= q <= 100", "At most 100 pushes."],
    hint: "One inbox stack, one outbox stack; refill outbox from inbox only when outbox runs dry.",
    tests: [
      { input: "5\npush 1\npush 2\npeek\npop\nempty", output: "1\n1\nfalse" },
      { input: "4\npush 5\npop\nempty\nempty", output: "5\nfalse\ntrue" },
    ],
  },
  {
    title: "Backspace String Compare",
    difficulty: "Easy",
    topics: "String, Stack, Simulation",
    statement:
      "In these strings '#' erases the character immediately before it (backspace); erased characters cannot erase the eraser. Decide whether the two typed results match.",
    input: "Line 1: string `s`.\nLine 2: string `t` (lowercase letters and '#').",
    output: "Print `true` if the final texts are equal, else `false`.",
    constraints: ["1 <= lengths <= 200", "Only lowercase letters and '#'.", "Backspaces can empty a string entirely."],
    hint: "Build each final text with a stack (or scan backwards counting pending skips) and compare.",
    tests: [
      { input: "ab#c\nad#c", output: "true" },
      { input: "a#c\nb", output: "false" },
      { input: "a##\nc#d#", output: "true" },
    ],
  },
  {
    title: "Car Fleet",
    difficulty: "Medium",
    topics: "Array, Sorting, Stack, Monotonic Stack",
    statement:
      "Cars occupy distinct positions along one lane heading to `target`, each cruising at its own constant speed (positions given, speeds parallel). A faster car behind a slower one catches up and locks into a single fleet travelling at the leader's speed (they merge, never overtake). Count how many fleets reach the target.",
    input: "Line 1: integers `target n`.\nLine 2: `n` distinct start positions.\nLine 3: `n` speeds aligned with positions.",
    output: "Print the number of car fleets arriving at the target.",
    constraints: ["1 <= n <= 10^5", "0 < position[i] < target", "1 <= speed[i] <= 10^6"],
    hint: "Rank cars by start position descending; convert each to arrival time — a new fleet starts whenever an arrival time exceeds the running best ahead.",
    tests: [
      { input: "12 5\n10 8 0 5 3\n2 4 1 1 3", output: "3" },
      { input: "10 1\n3\n3", output: "1" },
      { input: "100 3\n0 2 4\n4 2 1", output: "1" },
    ],
  },
  {
    title: "Swap Nodes in Pairs",
    difficulty: "Medium",
    topics: "Linked List, Recursion",
    statement:
      "Swap every two adjacent nodes of the linked list (relink nodes, don't merely swap values) and print the resulting list. A lone trailing node stays put.",
    input: "Line 1: integer `n`.\nLine 2: `n` space-separated list values.",
    output: "The rearranged list, space-separated on one line.",
    constraints: ["0 <= n <= 100"],
    hint: "Anchor a dummy head; repeatedly grab the upcoming pair, rotate their links, and jump ahead two.",
    tests: [
      { input: "4\n1 2 3 4", output: "2 1 4 3" },
      { input: "0", output: "" },
      { input: "1\n1", output: "1" },
    ],
  },
  {
    title: "Reverse Nodes in K-Group",
    difficulty: "Hard",
    topics: "Linked List, Recursion",
    statement:
      "Reverse the nodes of the list in groups of `k`; if fewer than k nodes remain at the tail leave them untouched. Print the final list.",
    input: "Line 1: integers `n k`.\nLine 2: `n` space-separated list values.",
    output: "The rearranged list, space-separated on one line.",
    constraints: ["1 <= n <= 5000", "1 <= k <= n"],
    hint: "Count k nodes ahead before committing to a reversal; recursion (or careful iteration with a group predecessor) keeps links straight.",
    tests: [
      { input: "5 2\n1 2 3 4 5", output: "2 1 4 3 5" },
      { input: "5 3\n1 2 3 4 5", output: "3 2 1 4 5" },
      { input: "5 6\n1 2 3 4 5", output: "1 2 3 4 5" },
    ],
  },
  {
    title: "Palindrome Linked List",
    difficulty: "Easy",
    topics: "Linked List, Two Pointers, Recursion",
    statement:
      "Decide whether the linked list's values form a palindrome. Follow-up: O(n) time and O(1) extra space via reverse-the-back-half.",
    input: "Line 1: integer `n`.\nLine 2: `n` space-separated list values.",
    output: "Print `true` if palindromic, else `false`.",
    constraints: ["1 <= n <= 10^5", "0 <= node values <= 9"],
    hint: "Find the middle with fast/slow pointers, reverse the second half, compare halves node by node.",
    tests: [
      { input: "4\n1 2 2 1", output: "true" },
      { input: "2\n1 2", output: "false" },
      { input: "1\n7", output: "true" },
    ],
  },
  {
    title: "Odd Even Linked List",
    difficulty: "Medium",
    topics: "Linked List",
    statement:
      "Group all nodes at odd positions (1st, 3rd, ...) followed by nodes at even positions, preserving relative order inside each group. Positions are 1-based. Print the reassembled list.",
    input: "Line 1: integer `n`.\nLine 2: `n` space-separated list values.",
    output: "The reordered list, space-separated on one line.",
    constraints: ["0 <= n <= 10^4"],
    hint: "Weave two chains simultaneously — oddTail.next = evenHead is what stitches them together at the end.",
    tests: [
      { input: "5\n1 2 3 4 5", output: "1 3 5 2 4" },
      { input: "7\n2 1 3 5 6 4 7", output: "2 3 6 7 1 5 4" },
      { input: "0", output: "" },
    ],
  },
  {
    title: "Intersection of Two Linked Lists",
    difficulty: "Easy",
    topics: "Linked List, Two Pointers, Hash Table",
    statement:
      "Two singly linked lists merge into a shared suffix at some node (reference equality, not just equal values). Given each list's own prefix plus their common suffix, report the value carried by the intersection node. If the lists never intersect the tests won't ask.",
    input: "Line 1: prefix values of list A (space-separated).\nLine 2: prefix values of list B.\nLine 3: common suffix values (at least one value). Either prefix may be empty.",
    output: "Print the value at the intersection node (first node of the shared suffix).",
    constraints: ["0 <= prefix lengths, suffix length >= 1", "Node values up to 10^5."],
    hint: "Pointer switching is the elegant trick: when either pointer falls off its end, reroute it to the other head — they meet at the intersection after equal distance.",
    tests: [
      { input: "4 1\n5 6 1\n8 4 5", output: "8" },
      { input: "\n\n7", output: "7" },
      { input: "2 6 4\n1 5\n3", output: "3" },
    ],
  },
  {
    title: "Sort List",
    difficulty: "Medium",
    topics: "Linked List, Two Pointers, Divide and Conquer, Sorting",
    statement:
      "Sort a linked list in ascending order. Target O(n log n) time with constant extra space — merge sort with a fast/slow split.",
    input: "Line 1: integer `n`.\nLine 2: `n` space-separated list values.",
    output: "The sorted list, space-separated on one line.",
    constraints: ["0 <= n <= 5*10^4", "-10^5 <= node values <= 10^5"],
    hint: "Cut the list at the midpoint, sort both halves recursively, then merge them the way Merge Two Sorted Lists does.",
    tests: [
      { input: "5\n-1 5 3 4 0", output: "-1 0 3 4 5" },
      { input: "1\n1", output: "1" },
      { input: "6\n3 1 2 6 5 4", output: "1 2 3 4 5 6" },
    ],
  },
  {
    title: "Merge K Sorted Lists",
    difficulty: "Hard",
    topics: "Linked List, Divide and Conquer, Heap",
    statement:
      "Given k individually sorted linked lists (each non-empty in our tests), weave them into one fully sorted list.",
    input: "Line 1: integer `k`.\nNext `k` lines: one sorted list per line, values space-separated. Every list has at least one value.",
    output: "The merged sorted values, space-separated on one line.",
    constraints: ["1 <= k <= 10^4", "Total nodes <= 10^4", "-10^4 <= values <= 10^4"],
    hint: "Min-heap seeded with each list's head pops the global smallest in O(log k); pairwise divide-and-conquer merging works too.",
    tests: [
      { input: "3\n1 4 5\n1 3 4\n2 6", output: "1 1 2 3 4 4 5 6" },
      { input: "2\n0\n2 5", output: "0 2 5" },
      { input: "1\n42", output: "42" },
    ],
  },
  {
    title: "Partition List",
    difficulty: "Medium",
    topics: "Linked List, Two Pointers",
    statement:
      "Reorder the list so every node with value < x precedes all others, keeping each region in original relative order (stable partition). Print the result.",
    input: "Line 1: integers `n x`.\nLine 2: `n` space-separated list values.",
    output: "The partitioned list, space-separated on one line.",
    constraints: ["0 <= n <= 200", "-100 <= values, x <= 100"],
    hint: "Thread nodes onto two separate lists (before / since x) while walking once, then join them.",
    tests: [
      { input: "6 3\n1 4 3 2 5 2", output: "1 2 2 4 3 5" },
      { input: "2 2\n2 1", output: "1 2" },
      { input: "1 5\n9", output: "9" },
    ],
  },
  {
    title: "Remove Duplicates from Sorted List II",
    difficulty: "Medium",
    topics: "Linked List, Two Pointers",
    statement:
      "From a sorted list delete EVERY node whose value occurs more than once (not just extras) and print what survives.",
    input: "Line 1: integer `n`.\nLine 2: `n` non-decreasing list values.",
    output: "The cleaned list, space-separated on one line (may be empty).",
    constraints: ["0 <= n <= 300", "-100 <= values <= 100"],
    hint: "A dummy head plus lookahead: whenever the next two nodes agree, sprint past the whole duplicate run.",
    tests: [
      { input: "7\n1 2 3 3 4 4 5", output: "1 2 5" },
      { input: "5\n1 1 1 2 3", output: "2 3" },
      { input: "3\n1 1 1", output: "" },
    ],
  },
];
