// Batch 2, Part D: Arrays, Strings, Matrix, Hashing, Math & Bits
// All statements, formats and tests are authored for ChainCode (stdin/stdout judging).
export const problemsD = [
  {
    title: "Two Sum",
    difficulty: "Easy",
    topics: "Array, Hash Table",
    statement:
      "Given an array of integers and a target, return the indices of the two numbers that add up to the target. Each input is crafted to have **exactly one** valid answer, and the same element may not be used twice. Indices are 0-based; print the smaller index first.",
    input: "Line 1: integers `n target`.\nLine 2: `n` space-separated integers.",
    output: "Print the two indices (smaller first) space-separated.",
    constraints: ["2 <= n <= 10^4", "-10^9 <= nums[i], target <= 10^9", "Exactly one valid pair exists."],
    hint: "Walk the array once storing value→index in a hash map; for each element check whether its partner already appeared.",
    tests: [
      { input: "4 9\n2 7 11 15", output: "0 1" },
      { input: "3 6\n3 2 4", output: "1 2" },
      { input: "2 6\n3 3", output: "0 1" },
    ],
  },
  {
    title: "Best Time to Buy and Sell Stock II",
    difficulty: "Medium",
    topics: "Array, Greedy, DP",
    statement:
      "You may buy and sell the stock any number of times, but you can hold at most one share at a time (must sell before buying again). Given daily prices, maximise total profit. You may buy and sell on the same day, which nets zero.",
    input: "Line 1: integer `n`.\nLine 2: `n` space-separated prices.",
    output: "Print the maximum achievable profit.",
    constraints: ["1 <= n <= 3*10^4", "0 <= prices[i] <= 10^4"],
    hint: "Every upward price step between consecutive days is free money — summing all positive differences is optimal.",
    tests: [
      { input: "6\n7 1 5 3 6 4", output: "7" },
      { input: "5\n1 2 3 4 5", output: "4" },
      { input: "5\n7 6 4 3 1", output: "0" },
    ],
  },
  {
    title: "Group Anagrams",
    difficulty: "Medium",
    topics: "Hash Table, String, Sorting",
    statement:
      "Group the words that are anagrams of each other (same letters, possibly rearranged). Output each group on one line with its members sorted alphabetically, and order the groups by their alphabetically smallest member.",
    input: "Line 1: integer `m`.\nLine 2: `m` space-separated lowercase words.",
    output: "One group per line (members sorted alphabetically), groups ordered by their first member.",
    constraints: ["1 <= m <= 10^4", "0 <= word length <= 100"],
    hint: "Sorting a word's letters gives a canonical key — every anagram collapses to the same key in a hash map.",
    tests: [
      { input: "6\neat tea tan ate nat bat", output: "ate eat tea\nbat\nnat tan" },
      { input: "1\na", output: "a" },
      { input: "2\nabc cab", output: "abc cab" },
    ],
  },
  {
    title: "Pascal's Triangle",
    difficulty: "Easy",
    topics: "Array, DP",
    statement:
      "Each entry of Pascal's triangle is the sum of the two entries above it; row edges are 1. Print the first `numRows` rows.",
    input: "One line: integer `numRows`.",
    output: "`numRows` lines, row `i` containing `i` space-separated values.",
    constraints: ["1 <= numRows <= 30"],
    hint: "Build each row from the previous one; only the interior positions need summing.",
    tests: [
      { input: "5", output: "1\n1 1\n1 2 1\n1 3 3 1\n1 4 6 4 1" },
      { input: "1", output: "1" },
      { input: "2", output: "1\n1 1" },
    ],
  },
  {
    title: "Rotate Image",
    difficulty: "Medium",
    topics: "Matrix, Math",
    statement:
      "Rotate the given square matrix 90 degrees clockwise, in place conceptually, and print the result.",
    input: "Line 1: integer `n`.\nNext `n` lines: `n` space-separated integers.",
    output: "The rotated matrix, one row per line, values space-separated.",
    constraints: ["1 <= n <= 20", "-100 <= matrix[i][j] <= 100"],
    hint: "Transpose across the main diagonal, then reverse each row — two reflections compose into a rotation.",
    tests: [
      { input: "3\n1 2 3\n4 5 6\n7 8 9", output: "7 4 1\n8 5 2\n9 6 3" },
      { input: "4\n5 1 9 11\n2 4 8 10\n13 3 6 7\n15 14 12 16", output: "15 13 2 5\n14 3 4 1\n12 6 8 9\n16 7 10 11" },
      { input: "1\n7", output: "7" },
    ],
  },
  {
    title: "Spiral Matrix",
    difficulty: "Medium",
    topics: "Matrix, Simulation",
    statement:
      "Traverse an m×n matrix in spiral order: right along the top row, down the right column, left along the bottom, up the left column, then repeat inward until every cell is visited.",
    input: "Line 1: integers `m n`.\nNext `m` lines: `n` space-separated integers.",
    output: "All elements in spiral order, space-separated on one line.",
    constraints: ["1 <= m, n <= 10", "-100 <= matrix[i][j] <= 100"],
    hint: "Maintain four shrinking boundaries (top, bottom, left, right) and peel one ring at a time.",
    tests: [
      { input: "3 3\n1 2 3\n4 5 6\n7 8 9", output: "1 2 3 6 9 8 7 4 5" },
      { input: "3 4\n1 2 3 4\n5 6 7 8\n9 10 11 12", output: "1 2 3 4 8 12 11 10 9 5 6 7" },
      { input: "1 1\n42", output: "42" },
    ],
  },
  {
    title: "Search a 2D Matrix",
    difficulty: "Medium",
    topics: "Matrix, Binary Search",
    statement:
      "A matrix has special ordering: every row is sorted ascending, and the first value of each row is greater than the last value of the previous row. Decide whether `target` appears.",
    input: "Line 1: integers `m n`.\nNext `m` lines: `n` space-separated integers.\nLast line: integer `target`.",
    output: "Print `true` if the target exists in the matrix, else `false`.",
    constraints: ["1 <= m, n <= 100", "-10^4 <= values, target <= 10^4"],
    hint: "Treat the matrix as one flattened sorted array of length m*n and binary search it via div/mod indexing.",
    tests: [
      { input: "3 4\n1 3 5 7\n10 11 16 20\n23 30 34 60\n3", output: "true" },
      { input: "3 4\n1 3 5 7\n10 11 16 20\n23 30 34 60\n13", output: "false" },
      { input: "1 1\n1\n1", output: "true" },
    ],
  },
  {
    title: "Rotate Array",
    difficulty: "Medium",
    topics: "Array, Math, Two Pointers",
    statement:
      "Rotate the array to the right by `k` steps, where each step shifts every element one position right (the last wraps to the front). Print the rotated array. Aim for O(1) extra space if you can.",
    input: "Line 1: integers `n k`.\nLine 2: `n` space-separated integers.",
    output: "The rotated array, space-separated on one line.",
    constraints: ["1 <= n <= 10^5", "0 <= k <= 10^5"],
    hint: "Reverse the whole array, then reverse the first k and the remaining n−k elements separately.",
    tests: [
      { input: "7 3\n1 2 3 4 5 6 7", output: "5 6 7 1 2 3 4" },
      { input: "6 2\n-1 -100 3 99 0 5", output: "0 5 -1 -100 3 99" },
      { input: "1 0\n9", output: "9" },
    ],
  },
  {
    title: "Merge Sorted Array",
    difficulty: "Easy",
    topics: "Array, Two Pointers, Sorting",
    statement:
      "Two individually sorted arrays are given. Merge them into a single sorted array (ties keep the element from the first array first).",
    input: "Line 1: integers `m n`.\nLine 2: `m` sorted integers.\nLine 3: `n` sorted integers.",
    output: "The merged sorted array, space-separated on one line.",
    constraints: ["0 <= m, n <= 200", "Both input arrays are non-decreasing.", "-10^9 <= values <= 10^9"],
    hint: "Merge from the back: repeatedly place the larger of the two trailing elements to avoid shifting anything.",
    tests: [
      { input: "3 3\n1 2 3\n2 5 6", output: "1 2 2 3 5 6" },
      { input: "1 0\n1", output: "1" },
      { input: "2 2\n1 1\n1 2", output: "1 1 1 2" },
    ],
  },
  {
    title: "Remove Duplicates from Sorted Array",
    difficulty: "Easy",
    topics: "Array, Two Pointers",
    statement:
      "Sorted array with duplicates: keep one copy of each distinct value at the front (order preserved). Report how many distinct values remain.",
    input: "Line 1: integer `n`.\nLine 2: `n` non-decreasing integers.",
    output: "Line 1: the count `k` of distinct values.\nLine 2: those `k` values space-separated.",
    constraints: ["0 <= n <= 3*10^4", "-100 <= nums[i] <= 100", "Input is non-decreasing."],
    hint: "Two pointers: one scans, one marks where the next fresh value belongs.",
    tests: [
      { input: "7\n0 0 1 1 1 2 2", output: "3\n0 1 2" },
      { input: "10\n0 0 1 1 1 2 2 3 3 4", output: "5\n0 1 2 3 4" },
      { input: "1\n5", output: "1\n5" },
    ],
  },
  {
    title: "Remove Element",
    difficulty: "Easy",
    topics: "Array, Two Pointers",
    statement:
      "Remove all occurrences of `val` while preserving the relative order of the surviving elements at the front. Report how many survive.",
    input: "Line 1: integers `n val`.\nLine 2: `n` space-separated integers.",
    output: "Line 1: the count `k` of kept elements.\nLine 2: the kept `k` values (original order) space-separated.",
    constraints: ["0 <= n <= 100", "0 <= val, nums[i] <= 50"],
    hint: "A write-pointer copies over every element that differs from val; everything behind it is final.",
    tests: [
      { input: "4 3\n3 2 2 3", output: "2\n2 2" },
      { input: "8 2\n0 1 2 2 3 0 4 2", output: "5\n0 1 3 0 4" },
      { input: "2 1\n1 1", output: "0\n" },
    ],
  },
  {
    title: "Next Permutation",
    difficulty: "Medium",
    topics: "Array, Two Pointers, Math",
    statement:
      "Rearrange the numbers into the next lexicographic permutation of their values. If no such arrangement exists (the sequence is descending), jump to the lowest possible permutation instead. The replacement must be done in place conceptually — print the result.",
    input: "Line 1: integer `n`.\nLine 2: `n` space-separated integers.",
    output: "The next permutation, space-separated on one line.",
    constraints: ["1 <= n <= 100", "0 <= nums[i] <= 100"],
    hint: "Scan from the right for the first drop, swap it with the smallest larger value to its right, then reverse the suffix.",
    tests: [
      { input: "3\n1 2 3", output: "1 3 2" },
      { input: "4\n1 1 5 1", output: "1 5 1 1" },
      { input: "3\n3 2 1", output: "1 2 3" },
    ],
  },
  {
    title: "Longest Palindromic Substring",
    difficulty: "Medium",
    topics: "String, DP, Expand Around Center",
    statement:
      "Find the longest run of consecutive characters inside the string that reads the same forwards and backwards. If several palindromes tie for the longest length, print the **leftmost** one.",
    input: "One line: string `s` (lowercase letters, non-empty).",
    output: "Print the longest palindromic substring.",
    constraints: ["1 <= s.length <= 1000"],
    hint: "Every palindrome has a center — try all 2n−1 centers (single char or gap) and expand outward while characters match.",
    tests: [
      { input: "babad", output: "bab" },
      { input: "cbbd", output: "bb" },
      { input: "ac", output: "a" },
    ],
  },
  {
    title: "Palindromic Substrings",
    difficulty: "Medium",
    topics: "String, DP, Expand Around Center",
    statement:
      "Count how many substrings (contiguous runs) of the string are palindromes. Substrings with different start or end indices count separately even if their text matches.",
    input: "One line: string `s` (lowercase letters).",
    output: "Print the number of palindromic substrings.",
    constraints: ["1 <= s.length <= 1000"],
    hint: "Same center-expansion as longest palindromic substring — but this time every successful expansion step adds one to the count.",
    tests: [
      { input: "abc", output: "3" },
      { input: "aaa", output: "6" },
      { input: "abba", output: "6" },
    ],
  },
  {
    title: "Valid Palindrome II",
    difficulty: "Easy",
    topics: "String, Greedy, Two Pointers",
    statement:
      "Decide whether the lowercase string becomes a palindrome after deleting **at most one** character.",
    input: "One line: string `s`.",
    output: "Print `true` if it can become a palindrome with at most one deletion, else `false`.",
    constraints: ["1 <= s.length <= 10^5"],
    hint: "Match inward with two pointers; at the first mismatch try skipping either side once and verify the rest.",
    tests: [
      { input: "aba", output: "true" },
      { input: "abca", output: "true" },
      { input: "abc", output: "false" },
    ],
  },
  {
    title: "Roman to Integer",
    difficulty: "Easy",
    topics: "Hash Table, Math, String",
    statement:
      "Roman numerals use symbols I=1, V=5, X=10, L=50, C=100, D=500, M=1000, written largest-to-smallest except when a smaller symbol precedes a larger one (then it subtracts: IV=4, IX=9, XL=40, XC=90, CD=400, CM=900). Convert a valid roman numeral to its integer value.",
    input: "One line: a valid roman numeral (uppercase, 1–15 symbols).",
    output: "Print its integer value.",
    constraints: ["The numeral represents a value from 1 to 3999."],
    hint: "Scan left to right: add each symbol's value, but subtract double when the next symbol is bigger.",
    tests: [
      { input: "III", output: "3" },
      { input: "LVIII", output: "58" },
      { input: "MCMXCIV", output: "1994" },
    ],
  },
  {
    title: "Integer to Roman",
    difficulty: "Medium",
    topics: "Hash Table, Math, String",
    statement:
      "Convert an integer to its roman numeral representation using the standard subtractive notation (IV=4, IX=9, XL=40, XC=90, CD=400, CM=900).",
    input: "One line: integer `num`.",
    output: "Print the roman numeral (uppercase).",
    constraints: ["1 <= num <= 3999"],
    hint: "Greedily peel off the largest symbol whose value fits — a table of 13 value/symbol pairs suffices.",
    tests: [
      { input: "3", output: "III" },
      { input: "58", output: "LVIII" },
      { input: "1994", output: "MCMXCIV" },
    ],
  },
  {
    title: "Longest Common Prefix",
    difficulty: "Easy",
    topics: "String, Trie",
    statement:
      "Find the longest prefix shared by every word in the list. It may be empty.",
    input: "Line 1: integer `m`.\nLine 2: `m` space-separated lowercase words.",
    output: "Print the common prefix (an empty line if there is none).",
    constraints: ["1 <= m <= 200", "0 <= word length <= 200"],
    hint: "Use the first word as candidate and shave its tail whenever another word disagrees at some position.",
    tests: [
      { input: "3\nflower flow flight", output: "fl" },
      { input: "3\ndog racecar car", output: "" },
      { input: "1\nsolo", output: "solo" },
    ],
  },
  {
    title: "Reverse Words in a String",
    difficulty: "Medium",
    topics: "String, Two Pointers",
    statement:
      "Rearrange a sentence so its words appear in reverse order. Collapse any runs of spaces to single separators and trim the ends.",
    input: "One line: the sentence (letters, digits and spaces).",
    output: "Print the words reversed, joined by exactly one space.",
    constraints: ["1 <= s.length <= 10^4", "Contains at least one word."],
    hint: "Split on whitespace, filter out empties, then join the tokens back-to-front.",
    tests: [
      { input: "the sky is blue", output: "blue is sky the" },
      { input: "  hello world  ", output: "hello world" },
      { input: "a good   example", output: "example good a" },
    ],
  },
  {
    title: "String to Integer (atoi)",
    difficulty: "Medium",
    topics: "String, Simulation",
    statement:
      "Parse a leading integer from a string, mimicking classic `atoi`: skip leading spaces; read an optional '+' or '-'; read digits until they stop; ignore everything after. If no digits follow the sign (or the string starts elsewhere), the value is 0. Clamp the result to the 32-bit signed range [−2147483648, 2147483647].",
    input: "One line: the string (may contain letters, digits, spaces, signs).",
    output: "Print the parsed (and clamped) integer.",
    constraints: ["0 <= s.length <= 200", "Characters: digits, latin letters, ' ', '+', '-', '.'."],
    hint: "Handle states in order: whitespace → sign → digits; detect overflow before it happens by comparing against the clamp bound divided by ten.",
    tests: [
      { input: "42", output: "42" },
      { input: "   -42", output: "-42" },
      { input: "4193 with words", output: "4193" },
      { input: "words and 987", output: "0" },
      { input: "-91283472332", output: "-2147483648" },
    ],
  },
  {
    title: "Compare Version Numbers",
    difficulty: "Medium",
    topics: "String, Two Pointers",
    statement:
      "Version strings are dot-separated revision numbers (`1.01`, `1.0.0`). Compare them revision by revision numerically — missing revisions count as zero — and report which version is greater.",
    input: "Line 1: version1.\nLine 2: version2. Revisions are non-negative integers without leading sign.",
    output: "Print `1` if version1 > version2, `-1` if less, `0` if equal.",
    constraints: ["1 <= versions length <= 500", "Revisions fit in 64-bit."],
    hint: "Split on dots and walk both lists together, treating absent revisions as 0 — compare parsed integers, never strings.",
    tests: [
      { input: "1.01\n1.001", output: "0" },
      { input: "1.0\n1.0.0", output: "0" },
      { input: "0.1\n1.1", output: "-1" },
      { input: "1.2\n1.10", output: "-1" },
    ],
  },
  {
    title: "Length of Last Word",
    difficulty: "Easy",
    topics: "String",
    statement:
      "Return the number of letters in the final word of the sentence (words are separated by spaces; trailing spaces may exist).",
    input: "One line: the sentence (letters and spaces).",
    output: "Print the length of the last word.",
    constraints: ["1 <= s.length <= 10^4", "At least one word exists."],
    hint: "Trim trailing spaces, then measure backwards from the end until the next space.",
    tests: [
      { input: "Hello World", output: "5" },
      { input: "   fly me   to   the moon  ", output: "4" },
      { input: "luffy is still joyboy", output: "6" },
    ],
  },
  {
    title: "Insert Delete GetRandom O(1)",
    difficulty: "Medium",
    topics: "Hash Table, Design, Math",
    statement:
      "Design a set supporting insert, remove and uniform-random element retrieval, each in average O(1). Duplicates behave like a set: inserting an existing value returns false, removing a missing value returns false. Simulate operations; `random` is only ever issued while exactly one element remains, so answers are deterministic.",
    input: "Line 1: integer `q`.\nNext `q` lines: `insert x`, `remove x` or `random`. `random` is never called on an empty set.",
    output: "For each operation print `true`/`false` for insert/remove, or the lone element for `random`.",
    constraints: ["1 <= q <= 2*10^5", "-2^31 <= x <= 2^31 - 1"],
    hint: "Combine a dynamic array with a hash map from value to its index; removal swaps the victim with the tail before popping.",
    tests: [
      { input: "6\ninsert 1\nremove 2\nrandom\ninsert 2\nremove 1\nrandom", output: "true\nfalse\n1\ntrue\ntrue\n2" },
      { input: "5\ninsert 5\ninsert 5\nremove 5\ninsert 7\nrandom", output: "true\nfalse\ntrue\ntrue\n7" },
    ],
  },
  {
    title: "Summary Ranges",
    difficulty: "Easy",
    topics: "Array",
    statement:
      "Compress a sorted distinct array into minimal ranges: maximal runs of consecutive values become `start->end`, isolated values stay bare.",
    input: "Line 1: integer `n`.\nLine 2: `n` sorted distinct integers.",
    output: "One range per line, in increasing order, formatted as `start->end` or just `value`.",
    constraints: ["0 <= n <= 20", "-2^31 <= nums[i] <= 2^31 - 1", "Values are sorted and unique."],
    hint: "Extend the current run while the next value equals current+1; close and emit the range when it breaks.",
    tests: [
      { input: "6\n0 1 2 4 5 7", output: "0->2\n4->5\n7" },
      { input: "1\n0", output: "0" },
      { input: "0", output: "" },
    ],
  },
  {
    title: "Plus One",
    difficulty: "Easy",
    topics: "Array, Math",
    statement:
      "An integer's digits are stored most-significant-first in an array. Add one to the number and print the resulting digit array (which may grow).",
    input: "Line 1: integer `n`.\nLine 2: `n` decimal digits (each 0–9), most significant first.",
    output: "The resulting digits, space-separated on one line.",
    constraints: ["1 <= n <= 100", "digits[i] is 0-9", "No leading zeros unless the number itself is a single 0."],
    hint: "Propagate the carry from the last digit forward; if a carry survives past digit zero, prepend a 1.",
    tests: [
      { input: "3\n1 2 3", output: "1 2 4" },
      { input: "4\n4 3 2 1", output: "4 3 2 2" },
      { input: "1\n9", output: "1 0" },
    ],
  },
  {
    title: "Add Binary",
    difficulty: "Easy",
    topics: "String, Math, Bit Manipulation",
    statement:
      "Add two binary numbers given as strings and print the sum in binary (no leading zeros).",
    input: "Line 1: binary string `a`.\nLine 2: binary string `b`.",
    output: "Print the binary sum.",
    constraints: ["1 <= lengths <= 10^4", "Strings contain only '0'/'1' and have no leading zeros (except the value 0 itself)."],
    hint: "Add from the least significant ends with a carry bit — pad mentally with zeros when one string runs dry.",
    tests: [
      { input: "11\n1", output: "100" },
      { input: "1010\n1011", output: "10101" },
      { input: "0\n0", output: "0" },
    ],
  },
  {
    title: "Add Strings",
    difficulty: "Easy",
    topics: "String, Math",
    statement:
      "Add two non-negative decimal numbers given as strings (they may exceed any built-in type) and print the sum as a string.",
    input: "Line 1: decimal string `num1`.\nLine 2: decimal string `num2`.",
    output: "Print the decimal sum (no leading zeros).",
    constraints: ["1 <= lengths <= 10^4", "Digits only, no leading zeros (except the number 0 itself)."],
    hint: "Grade-school column addition from both tails with a carry — never convert the whole strings to numbers.",
    tests: [
      { input: "456\n77", output: "533" },
      { input: "0\n0", output: "0" },
      { input: "999999999999999999999999\n1", output: "1000000000000000000000000" },
    ],
  },
  {
    title: "Palindrome Number",
    difficulty: "Easy",
    topics: "Math",
    statement:
      "Decide whether an integer reads the same forwards and backwards. Negative numbers are never palindromes because of the minus sign.",
    input: "One line: integer `x`.",
    output: "Print `true` or `false`.",
    constraints: ["-2^31 <= x <= 2^31 - 1"],
    hint: "Reverse half the number arithmetically and compare halves — avoids overflow and string conversion entirely.",
    tests: [
      { input: "121", output: "true" },
      { input: "-121", output: "false" },
      { input: "10", output: "false" },
    ],
  },
  {
    title: "Reverse Integer",
    difficulty: "Medium",
    topics: "Math",
    statement:
      "Reverse the digits of a signed 32-bit integer. If the reversed value falls outside [−2147483648, 2147483647], print 0 instead.",
    input: "One line: integer `x`.",
    output: "Print the reversed (possibly clamped-to-zero) integer.",
    constraints: ["-2^31 <= x <= 2^31 - 1"],
    hint: "Pop digits off the tail and push them onto the result; test the bound BEFORE multiplying by ten, not after.",
    tests: [
      { input: "123", output: "321" },
      { input: "-123", output: "-321" },
      { input: "120", output: "21" },
      { input: "1534236469", output: "0" },
    ],
  },
  {
    title: "Count Primes",
    difficulty: "Medium",
    topics: "Math, Number Theory, Sieve",
    statement:
      "Count how many prime numbers are strictly less than `n`.",
    input: "One line: non-negative integer `n`.",
    output: "Print the count of primes below n.",
    constraints: ["0 <= n <= 5*10^6"],
    hint: "Sieve of Eratosthenes: mark multiples starting from each prime's square; unmarked survivors are primes.",
    tests: [
      { input: "10", output: "4" },
      { input: "0", output: "0" },
      { input: "1", output: "0" },
      { input: "100", output: "25" },
    ],
  },
  {
    title: "Happy Number",
    difficulty: "Easy",
    topics: "Hash Table, Math, Two Pointers",
    statement:
      "Repeatedly replace the number with the sum of the squares of its digits. The process either settles at 1 (a happy number) or loops forever among other values. Decide which fate awaits `n`.",
    input: "One line: positive integer `n`.",
    output: "Print `true` if n eventually reaches 1, else `false`.",
    constraints: ["1 <= n <= 2^31 - 1"],
    hint: "Track seen sums in a hash set — revisiting a value proves a cycle — or race slow/fast pointers like cycle detection in a list.",
    tests: [
      { input: "19", output: "true" },
      { input: "2", output: "false" },
      { input: "7", output: "true" },
    ],
  },
  {
    title: "Power of Two",
    difficulty: "Easy",
    topics: "Math, Bit Manipulation",
    statement:
      "Decide whether an integer is an exact power of two (2^0 = 1 counts).",
    input: "One line: integer `n`.",
    output: "Print `true` or `false`.",
    constraints: ["-2^31 <= n <= 2^31 - 1"],
    hint: "In binary a power of two has a single set bit — check positivity plus the trick n & (n−1) == 0.",
    tests: [
      { input: "1", output: "true" },
      { input: "16", output: "true" },
      { input: "3", output: "false" },
      { input: "-2", output: "false" },
    ],
  },
  {
    title: "Fizz Buzz",
    difficulty: "Easy",
    topics: "Math, String, Simulation",
    statement:
      "For every integer from 1 to n print one token: `FizzBuzz` when divisible by both 3 and 5, `Fizz` when divisible by 3, `Buzz` when divisible by 5, otherwise the number itself.",
    input: "One line: integer `n`.",
    output: "`n` lines, the i-th being the token for i.",
    constraints: ["1 <= n <= 10^4"],
    hint: "Check divisibility by 15 (or 3-and-5 together) first, otherwise the Fizz case swallows the combined one.",
    tests: [
      { input: "15", output: "1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz" },
      { input: "5", output: "1\n2\nFizz\n4\nBuzz" },
      { input: "1", output: "1" },
    ],
  },
  {
    title: "Reverse Bits",
    difficulty: "Easy",
    topics: "Bit Manipulation, Divide and Conquer",
    statement:
      "Treat the input as an unsigned 32-bit integer, flip the order of its bits, and print the resulting unsigned value.",
    input: "One line: integer `n` (0 <= n < 2^32).",
    output: "Print the bit-reversed unsigned 32-bit value.",
    constraints: ["0 <= n < 2^32"],
    hint: "Shift bits out of n from the bottom and into the result from the top, 32 times; or split-and-swap halves recursively.",
    tests: [
      { input: "43261596", output: "964176192" },
      { input: "2147483648", output: "1" },
      { input: "0", output: "0" },
    ],
  },
  {
    title: "Hamming Distance",
    difficulty: "Easy",
    topics: "Bit Manipulation",
    statement:
      "The Hamming distance between two integers is the number of bit positions where their binary representations differ (compare as 32-bit). Compute it for x and y.",
    input: "Line 1: integers `x y` (0 <= x, y < 2^31).",
    output: "Print the Hamming distance.",
    constraints: ["0 <= x, y < 2^31"],
    hint: "XOR marks differing bits with 1s — the answer is the popcount of x XOR y.",
    tests: [
      { input: "1 4", output: "2" },
      { input: "3 1", output: "1" },
      { input: "1577962638 1727613287", output: "12" },
    ],
  },
  {
    title: "Maximum Average Subarray I",
    difficulty: "Easy",
    topics: "Array, Sliding Window",
    statement:
      "Among all contiguous subarrays of length exactly `k`, find the maximum average of the elements.",
    input: "Line 1: integers `n k`.\nLine 2: `n` space-separated integers.",
    output: "Print the maximum average fixed to exactly five decimal places.",
    constraints: ["1 <= k <= n <= 10^5", "-10^4 <= nums[i] <= 10^4"],
    hint: "Slide a window: add the entering element, drop the leaving one, track the best window sum — division comes last.",
    tests: [
      { input: "6 4\n1 12 -5 -6 50 30", output: "12.75000" },
      { input: "1 1\n5", output: "5.00000" },
      { input: "5 2\n-1 -2 -3 -4 -5", output: "-1.50000" },
    ],
  },
];
